export const sampleFiles = [
	'african-pe-hi.wav',
	'african-pe-lo.wav',
	'african-pe-med.wav',
	'bendy.wav',
	'bigbend.wav',
	'blobble.wav',
	'bongo hi.wav',
	'bongo lo.wav',
	'crikix.wav',
	'djembe-side.wav',
	'electrotabla.wav',
	'ethnowhat.wav',
	'gungru.2.wav',
	'gungru1.wav',
	'gungru3.wav',
	'gungru5.wav',
	'long-tabla-hit.wav',
	'lotabla.wav',
	'pipechimes.wav',
	'rainstick.wav',
	'shekere-roll.wav',
	'shekere1.wav',
	'solid-tabla-hit.wav',
	'steeldrum.wav',
	'tabla-dum.wav',
	'tabla-hardhit.wav',
	'tablaesque.wav',
	'tambo-dum.wav',
	'tambo-tak.wav',
	'verby-cajon-bass.wav',
	'verby-cajon-high.wav',
	'verby-cajon-lo.wav',
	'verby-rattle.wav',
	'wavedrum1.wav',
	'wavedrum2.wav',
	'wavedrum3.wav',
];
